/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhonetiqueRouteImport } from './routes/phonetique'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulacrosIndexRouteImport } from './routes/simulacros.index'
import { Route as LeconsIndexRouteImport } from './routes/lecons.index'
import { Route as SimulacrosExamIdRouteImport } from './routes/simulacros.$examId'
import { Route as LeconsLessonIdRouteImport } from './routes/lecons.$lessonId'
import { Route as ApiSttRouteImport } from './routes/api.stt'
import { Route as ApiEvaluateRouteImport } from './routes/api.evaluate'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const PhonetiqueRoute = PhonetiqueRouteImport.update({
  id: '/phonetique',
  path: '/phonetique',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacrosIndexRoute = SimulacrosIndexRouteImport.update({
  id: '/simulacros/',
  path: '/simulacros/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconsIndexRoute = LeconsIndexRouteImport.update({
  id: '/lecons/',
  path: '/lecons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacrosExamIdRoute = SimulacrosExamIdRouteImport.update({
  id: '/simulacros/$examId',
  path: '/simulacros/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconsLessonIdRoute = LeconsLessonIdRouteImport.update({
  id: '/lecons/$lessonId',
  path: '/lecons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateRoute = ApiEvaluateRouteImport.update({
  id: '/api/evaluate',
  path: '/api/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/phonetique': typeof PhonetiqueRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/stt': typeof ApiSttRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/simulacros/$examId': typeof SimulacrosExamIdRoute
  '/lecons/': typeof LeconsIndexRoute
  '/simulacros/': typeof SimulacrosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/phonetique': typeof PhonetiqueRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/stt': typeof ApiSttRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/simulacros/$examId': typeof SimulacrosExamIdRoute
  '/lecons': typeof LeconsIndexRoute
  '/simulacros': typeof SimulacrosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/phonetique': typeof PhonetiqueRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/stt': typeof ApiSttRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/simulacros/$examId': typeof SimulacrosExamIdRoute
  '/lecons/': typeof LeconsIndexRoute
  '/simulacros/': typeof SimulacrosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/phonetique'
    | '/api/chat'
    | '/api/evaluate'
    | '/api/stt'
    | '/lecons/$lessonId'
    | '/simulacros/$examId'
    | '/lecons/'
    | '/simulacros/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/phonetique'
    | '/api/chat'
    | '/api/evaluate'
    | '/api/stt'
    | '/lecons/$lessonId'
    | '/simulacros/$examId'
    | '/lecons'
    | '/simulacros'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/phonetique'
    | '/api/chat'
    | '/api/evaluate'
    | '/api/stt'
    | '/lecons/$lessonId'
    | '/simulacros/$examId'
    | '/lecons/'
    | '/simulacros/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  PhonetiqueRoute: typeof PhonetiqueRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEvaluateRoute: typeof ApiEvaluateRoute
  ApiSttRoute: typeof ApiSttRoute
  LeconsLessonIdRoute: typeof LeconsLessonIdRoute
  SimulacrosExamIdRoute: typeof SimulacrosExamIdRoute
  LeconsIndexRoute: typeof LeconsIndexRoute
  SimulacrosIndexRoute: typeof SimulacrosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/phonetique': {
      id: '/phonetique'
      path: '/phonetique'
      fullPath: '/phonetique'
      preLoaderRoute: typeof PhonetiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacros/': {
      id: '/simulacros/'
      path: '/simulacros'
      fullPath: '/simulacros/'
      preLoaderRoute: typeof SimulacrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecons/': {
      id: '/lecons/'
      path: '/lecons'
      fullPath: '/lecons/'
      preLoaderRoute: typeof LeconsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacros/$examId': {
      id: '/simulacros/$examId'
      path: '/simulacros/$examId'
      fullPath: '/simulacros/$examId'
      preLoaderRoute: typeof SimulacrosExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecons/$lessonId': {
      id: '/lecons/$lessonId'
      path: '/lecons/$lessonId'
      fullPath: '/lecons/$lessonId'
      preLoaderRoute: typeof LeconsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate': {
      id: '/api/evaluate'
      path: '/api/evaluate'
      fullPath: '/api/evaluate'
      preLoaderRoute: typeof ApiEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  PhonetiqueRoute: PhonetiqueRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEvaluateRoute: ApiEvaluateRoute,
  ApiSttRoute: ApiSttRoute,
  LeconsLessonIdRoute: LeconsLessonIdRoute,
  SimulacrosExamIdRoute: SimulacrosExamIdRoute,
  LeconsIndexRoute: LeconsIndexRoute,
  SimulacrosIndexRoute: SimulacrosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
