/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PhonetiqueRouteImport } from './routes/phonetique'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalizadorRouteImport } from './routes/analizador'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimulacrosIndexRouteImport } from './routes/simulacros.index'
import { Route as LeconsIndexRouteImport } from './routes/lecons.index'
import { Route as SimulacrosExamIdRouteImport } from './routes/simulacros.$examId'
import { Route as LeconsLessonIdRouteImport } from './routes/lecons.$lessonId'
import { Route as ApiTtsRouteImport } from './routes/api.tts'
import { Route as ApiSttRouteImport } from './routes/api.stt'
import { Route as ApiEvaluateRouteImport } from './routes/api.evaluate'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthenticatedVocabularioRouteImport } from './routes/_authenticated/vocabulario'
import { Route as AuthenticatedRevisarRouteImport } from './routes/_authenticated/revisar'
import { Route as AuthenticatedProfessorRouteImport } from './routes/_authenticated/professor'
import { Route as AuthenticatedMiHistorialRouteImport } from './routes/_authenticated/mi-historial'
import { Route as AuthenticatedEscrituraRouteImport } from './routes/_authenticated/escritura'
import { Route as SimulacrosComprehensionIndexRouteImport } from './routes/simulacros.comprehension.index'
import { Route as AuthenticatedRoleplayIndexRouteImport } from './routes/_authenticated/roleplay.index'
import { Route as SimulacrosComprehensionExamIdRouteImport } from './routes/simulacros.comprehension.$examId'
import { Route as AuthenticatedRoleplayScenarioIdRouteImport } from './routes/_authenticated/roleplay.$scenarioId'

const PhonetiqueRoute = PhonetiqueRouteImport.update({
  id: '/phonetique',
  path: '/phonetique',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizadorRoute = AnalizadorRouteImport.update({
  id: '/analizador',
  path: '/analizador',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacrosIndexRoute = SimulacrosIndexRouteImport.update({
  id: '/simulacros/',
  path: '/simulacros/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconsIndexRoute = LeconsIndexRouteImport.update({
  id: '/lecons/',
  path: '/lecons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacrosExamIdRoute = SimulacrosExamIdRouteImport.update({
  id: '/simulacros/$examId',
  path: '/simulacros/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconsLessonIdRoute = LeconsLessonIdRouteImport.update({
  id: '/lecons/$lessonId',
  path: '/lecons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluateRoute = ApiEvaluateRouteImport.update({
  id: '/api/evaluate',
  path: '/api/evaluate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVocabularioRoute =
  AuthenticatedVocabularioRouteImport.update({
    id: '/vocabulario',
    path: '/vocabulario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRevisarRoute = AuthenticatedRevisarRouteImport.update({
  id: '/revisar',
  path: '/revisar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfessorRoute = AuthenticatedProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiHistorialRoute =
  AuthenticatedMiHistorialRouteImport.update({
    id: '/mi-historial',
    path: '/mi-historial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscrituraRoute = AuthenticatedEscrituraRouteImport.update({
  id: '/escritura',
  path: '/escritura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SimulacrosComprehensionIndexRoute =
  SimulacrosComprehensionIndexRouteImport.update({
    id: '/simulacros/comprehension/',
    path: '/simulacros/comprehension/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoleplayIndexRoute =
  AuthenticatedRoleplayIndexRouteImport.update({
    id: '/roleplay/',
    path: '/roleplay/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SimulacrosComprehensionExamIdRoute =
  SimulacrosComprehensionExamIdRouteImport.update({
    id: '/simulacros/comprehension/$examId',
    path: '/simulacros/comprehension/$examId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoleplayScenarioIdRoute =
  AuthenticatedRoleplayScenarioIdRouteImport.update({
    id: '/roleplay/$scenarioId',
    path: '/roleplay/$scenarioId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analizador': typeof AnalizadorRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/phonetique': typeof PhonetiqueRoute
  '/escritura': typeof AuthenticatedEscrituraRoute
  '/mi-historial': typeof AuthenticatedMiHistorialRoute
  '/professor': typeof AuthenticatedProfessorRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/vocabulario': typeof AuthenticatedVocabularioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/simulacros/$examId': typeof SimulacrosExamIdRoute
  '/lecons/': typeof LeconsIndexRoute
  '/simulacros/': typeof SimulacrosIndexRoute
  '/roleplay/$scenarioId': typeof AuthenticatedRoleplayScenarioIdRoute
  '/simulacros/comprehension/$examId': typeof SimulacrosComprehensionExamIdRoute
  '/roleplay/': typeof AuthenticatedRoleplayIndexRoute
  '/simulacros/comprehension/': typeof SimulacrosComprehensionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analizador': typeof AnalizadorRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/phonetique': typeof PhonetiqueRoute
  '/escritura': typeof AuthenticatedEscrituraRoute
  '/mi-historial': typeof AuthenticatedMiHistorialRoute
  '/professor': typeof AuthenticatedProfessorRoute
  '/revisar': typeof AuthenticatedRevisarRoute
  '/vocabulario': typeof AuthenticatedVocabularioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/simulacros/$examId': typeof SimulacrosExamIdRoute
  '/lecons': typeof LeconsIndexRoute
  '/simulacros': typeof SimulacrosIndexRoute
  '/roleplay/$scenarioId': typeof AuthenticatedRoleplayScenarioIdRoute
  '/simulacros/comprehension/$examId': typeof SimulacrosComprehensionExamIdRoute
  '/roleplay': typeof AuthenticatedRoleplayIndexRoute
  '/simulacros/comprehension': typeof SimulacrosComprehensionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analizador': typeof AnalizadorRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/phonetique': typeof PhonetiqueRoute
  '/_authenticated/escritura': typeof AuthenticatedEscrituraRoute
  '/_authenticated/mi-historial': typeof AuthenticatedMiHistorialRoute
  '/_authenticated/professor': typeof AuthenticatedProfessorRoute
  '/_authenticated/revisar': typeof AuthenticatedRevisarRoute
  '/_authenticated/vocabulario': typeof AuthenticatedVocabularioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/evaluate': typeof ApiEvaluateRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/lecons/$lessonId': typeof LeconsLessonIdRoute
  '/simulacros/$examId': typeof SimulacrosExamIdRoute
  '/lecons/': typeof LeconsIndexRoute
  '/simulacros/': typeof SimulacrosIndexRoute
  '/_authenticated/roleplay/$scenarioId': typeof AuthenticatedRoleplayScenarioIdRoute
  '/simulacros/comprehension/$examId': typeof SimulacrosComprehensionExamIdRoute
  '/_authenticated/roleplay/': typeof AuthenticatedRoleplayIndexRoute
  '/simulacros/comprehension/': typeof SimulacrosComprehensionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analizador'
    | '/auth'
    | '/chat'
    | '/phonetique'
    | '/escritura'
    | '/mi-historial'
    | '/professor'
    | '/revisar'
    | '/vocabulario'
    | '/api/chat'
    | '/api/evaluate'
    | '/api/stt'
    | '/api/tts'
    | '/lecons/$lessonId'
    | '/simulacros/$examId'
    | '/lecons/'
    | '/simulacros/'
    | '/roleplay/$scenarioId'
    | '/simulacros/comprehension/$examId'
    | '/roleplay/'
    | '/simulacros/comprehension/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analizador'
    | '/auth'
    | '/chat'
    | '/phonetique'
    | '/escritura'
    | '/mi-historial'
    | '/professor'
    | '/revisar'
    | '/vocabulario'
    | '/api/chat'
    | '/api/evaluate'
    | '/api/stt'
    | '/api/tts'
    | '/lecons/$lessonId'
    | '/simulacros/$examId'
    | '/lecons'
    | '/simulacros'
    | '/roleplay/$scenarioId'
    | '/simulacros/comprehension/$examId'
    | '/roleplay'
    | '/simulacros/comprehension'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analizador'
    | '/auth'
    | '/chat'
    | '/phonetique'
    | '/_authenticated/escritura'
    | '/_authenticated/mi-historial'
    | '/_authenticated/professor'
    | '/_authenticated/revisar'
    | '/_authenticated/vocabulario'
    | '/api/chat'
    | '/api/evaluate'
    | '/api/stt'
    | '/api/tts'
    | '/lecons/$lessonId'
    | '/simulacros/$examId'
    | '/lecons/'
    | '/simulacros/'
    | '/_authenticated/roleplay/$scenarioId'
    | '/simulacros/comprehension/$examId'
    | '/_authenticated/roleplay/'
    | '/simulacros/comprehension/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalizadorRoute: typeof AnalizadorRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  PhonetiqueRoute: typeof PhonetiqueRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEvaluateRoute: typeof ApiEvaluateRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  LeconsLessonIdRoute: typeof LeconsLessonIdRoute
  SimulacrosExamIdRoute: typeof SimulacrosExamIdRoute
  LeconsIndexRoute: typeof LeconsIndexRoute
  SimulacrosIndexRoute: typeof SimulacrosIndexRoute
  SimulacrosComprehensionExamIdRoute: typeof SimulacrosComprehensionExamIdRoute
  SimulacrosComprehensionIndexRoute: typeof SimulacrosComprehensionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/phonetique': {
      id: '/phonetique'
      path: '/phonetique'
      fullPath: '/phonetique'
      preLoaderRoute: typeof PhonetiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analizador': {
      id: '/analizador'
      path: '/analizador'
      fullPath: '/analizador'
      preLoaderRoute: typeof AnalizadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacros/': {
      id: '/simulacros/'
      path: '/simulacros'
      fullPath: '/simulacros/'
      preLoaderRoute: typeof SimulacrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecons/': {
      id: '/lecons/'
      path: '/lecons'
      fullPath: '/lecons/'
      preLoaderRoute: typeof LeconsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacros/$examId': {
      id: '/simulacros/$examId'
      path: '/simulacros/$examId'
      fullPath: '/simulacros/$examId'
      preLoaderRoute: typeof SimulacrosExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecons/$lessonId': {
      id: '/lecons/$lessonId'
      path: '/lecons/$lessonId'
      fullPath: '/lecons/$lessonId'
      preLoaderRoute: typeof LeconsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluate': {
      id: '/api/evaluate'
      path: '/api/evaluate'
      fullPath: '/api/evaluate'
      preLoaderRoute: typeof ApiEvaluateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vocabulario': {
      id: '/_authenticated/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof AuthenticatedVocabularioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/revisar': {
      id: '/_authenticated/revisar'
      path: '/revisar'
      fullPath: '/revisar'
      preLoaderRoute: typeof AuthenticatedRevisarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/professor': {
      id: '/_authenticated/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof AuthenticatedProfessorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-historial': {
      id: '/_authenticated/mi-historial'
      path: '/mi-historial'
      fullPath: '/mi-historial'
      preLoaderRoute: typeof AuthenticatedMiHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escritura': {
      id: '/_authenticated/escritura'
      path: '/escritura'
      fullPath: '/escritura'
      preLoaderRoute: typeof AuthenticatedEscrituraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/simulacros/comprehension/': {
      id: '/simulacros/comprehension/'
      path: '/simulacros/comprehension'
      fullPath: '/simulacros/comprehension/'
      preLoaderRoute: typeof SimulacrosComprehensionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roleplay/': {
      id: '/_authenticated/roleplay/'
      path: '/roleplay'
      fullPath: '/roleplay/'
      preLoaderRoute: typeof AuthenticatedRoleplayIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/simulacros/comprehension/$examId': {
      id: '/simulacros/comprehension/$examId'
      path: '/simulacros/comprehension/$examId'
      fullPath: '/simulacros/comprehension/$examId'
      preLoaderRoute: typeof SimulacrosComprehensionExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roleplay/$scenarioId': {
      id: '/_authenticated/roleplay/$scenarioId'
      path: '/roleplay/$scenarioId'
      fullPath: '/roleplay/$scenarioId'
      preLoaderRoute: typeof AuthenticatedRoleplayScenarioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEscrituraRoute: typeof AuthenticatedEscrituraRoute
  AuthenticatedMiHistorialRoute: typeof AuthenticatedMiHistorialRoute
  AuthenticatedProfessorRoute: typeof AuthenticatedProfessorRoute
  AuthenticatedRevisarRoute: typeof AuthenticatedRevisarRoute
  AuthenticatedVocabularioRoute: typeof AuthenticatedVocabularioRoute
  AuthenticatedRoleplayScenarioIdRoute: typeof AuthenticatedRoleplayScenarioIdRoute
  AuthenticatedRoleplayIndexRoute: typeof AuthenticatedRoleplayIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEscrituraRoute: AuthenticatedEscrituraRoute,
  AuthenticatedMiHistorialRoute: AuthenticatedMiHistorialRoute,
  AuthenticatedProfessorRoute: AuthenticatedProfessorRoute,
  AuthenticatedRevisarRoute: AuthenticatedRevisarRoute,
  AuthenticatedVocabularioRoute: AuthenticatedVocabularioRoute,
  AuthenticatedRoleplayScenarioIdRoute: AuthenticatedRoleplayScenarioIdRoute,
  AuthenticatedRoleplayIndexRoute: AuthenticatedRoleplayIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalizadorRoute: AnalizadorRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  PhonetiqueRoute: PhonetiqueRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEvaluateRoute: ApiEvaluateRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  LeconsLessonIdRoute: LeconsLessonIdRoute,
  SimulacrosExamIdRoute: SimulacrosExamIdRoute,
  LeconsIndexRoute: LeconsIndexRoute,
  SimulacrosIndexRoute: SimulacrosIndexRoute,
  SimulacrosComprehensionExamIdRoute: SimulacrosComprehensionExamIdRoute,
  SimulacrosComprehensionIndexRoute: SimulacrosComprehensionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
